# .github/workflows/test.yml
name: Test API
# When it's trigger
on:
  push:
    branches: master
  pull_request:
    branches: master
# Tasks
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    # To clone code to work on
    - name: clone
      run: git clone https://github.com/rothasok/devops-cadt-2-main.git
    - name: List folders
      run: ls

